// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_P
NumericMatrix get_P(NumericVector theta, int number_of_loci, int number_of_clusters);
RcppExport SEXP _disclapmix2_get_P(SEXP thetaSEXP, SEXP number_of_lociSEXP, SEXP number_of_clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_loci(number_of_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_clusters(number_of_clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(get_P(theta, number_of_loci, number_of_clusters));
    return rcpp_result_gen;
END_RCPP
}
// get_tau
NumericVector get_tau(NumericVector theta, int number_of_loci, int number_of_clusters);
RcppExport SEXP _disclapmix2_get_tau(SEXP thetaSEXP, SEXP number_of_lociSEXP, SEXP number_of_clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_loci(number_of_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_clusters(number_of_clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(get_tau(theta, number_of_loci, number_of_clusters));
    return rcpp_result_gen;
END_RCPP
}
// loglik_tau_p
double loglik_tau_p(NumericVector tau, NumericMatrix p_by_cluster_and_locus, IntegerMatrix db, IntegerMatrix y, int number_of_1_loci, int number_of_2_loci);
RcppExport SEXP _disclapmix2_loglik_tau_p(SEXP tauSEXP, SEXP p_by_cluster_and_locusSEXP, SEXP dbSEXP, SEXP ySEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type p_by_cluster_and_locus(p_by_cluster_and_locusSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type db(dbSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_tau_p(tau, p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci));
    return rcpp_result_gen;
END_RCPP
}
// loglik_tau_p_ns
double loglik_tau_p_ns(NumericVector tau, NumericMatrix p_by_cluster_and_locus, IntegerMatrix db, IntegerMatrix y, NumericMatrix pi, NumericMatrix q, int number_of_1_loci, int number_of_2_loci);
RcppExport SEXP _disclapmix2_loglik_tau_p_ns(SEXP tauSEXP, SEXP p_by_cluster_and_locusSEXP, SEXP dbSEXP, SEXP ySEXP, SEXP piSEXP, SEXP qSEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type p_by_cluster_and_locus(p_by_cluster_and_locusSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type db(dbSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_tau_p_ns(tau, p_by_cluster_and_locus, db, y, pi, q, number_of_1_loci, number_of_2_loci));
    return rcpp_result_gen;
END_RCPP
}
// neg_loglik_theta
double neg_loglik_theta(NumericVector theta, IntegerMatrix db, IntegerMatrix y, int number_of_1_loci, int number_of_2_loci);
RcppExport SEXP _disclapmix2_neg_loglik_theta(SEXP thetaSEXP, SEXP dbSEXP, SEXP ySEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type db(dbSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(neg_loglik_theta(theta, db, y, number_of_1_loci, number_of_2_loci));
    return rcpp_result_gen;
END_RCPP
}
// compute_profile_prs
NumericMatrix compute_profile_prs(NumericMatrix p_by_cluster_and_locus, IntegerMatrix db, IntegerMatrix y, int number_of_1_loci, int number_of_2_loci);
RcppExport SEXP _disclapmix2_compute_profile_prs(SEXP p_by_cluster_and_locusSEXP, SEXP dbSEXP, SEXP ySEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_by_cluster_and_locus(p_by_cluster_and_locusSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type db(dbSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_profile_prs(p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci));
    return rcpp_result_gen;
END_RCPP
}
// compute_profiles_pr_by_cluster_and_locus
List compute_profiles_pr_by_cluster_and_locus(NumericMatrix p_by_cluster_and_locus, IntegerMatrix x, IntegerMatrix y, int number_of_1_loci, int number_of_2_loci);
RcppExport SEXP _disclapmix2_compute_profiles_pr_by_cluster_and_locus(SEXP p_by_cluster_and_locusSEXP, SEXP xSEXP, SEXP ySEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_by_cluster_and_locus(p_by_cluster_and_locusSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_profiles_pr_by_cluster_and_locus(p_by_cluster_and_locus, x, y, number_of_1_loci, number_of_2_loci));
    return rcpp_result_gen;
END_RCPP
}
// compute_profile_prs_ns
NumericMatrix compute_profile_prs_ns(NumericMatrix p_by_cluster_and_locus, IntegerMatrix db, IntegerMatrix y, NumericMatrix pi, NumericMatrix q, int number_of_1_loci, int number_of_2_loci);
RcppExport SEXP _disclapmix2_compute_profile_prs_ns(SEXP p_by_cluster_and_locusSEXP, SEXP dbSEXP, SEXP ySEXP, SEXP piSEXP, SEXP qSEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p_by_cluster_and_locus(p_by_cluster_and_locusSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type db(dbSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_profile_prs_ns(p_by_cluster_and_locus, db, y, pi, q, number_of_1_loci, number_of_2_loci));
    return rcpp_result_gen;
END_RCPP
}
// compute_posterior_cluster_prs
NumericMatrix compute_posterior_cluster_prs(NumericMatrix profile_pr, NumericVector tau);
RcppExport SEXP _disclapmix2_compute_posterior_cluster_prs(SEXP profile_prSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type profile_pr(profile_prSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_posterior_cluster_prs(profile_pr, tau));
    return rcpp_result_gen;
END_RCPP
}
// neg_loglik_theta_ns
double neg_loglik_theta_ns(NumericVector theta, IntegerMatrix db, IntegerMatrix y, NumericMatrix pi, NumericMatrix q, int number_of_1_loci, int number_of_2_loci);
RcppExport SEXP _disclapmix2_neg_loglik_theta_ns(SEXP thetaSEXP, SEXP dbSEXP, SEXP ySEXP, SEXP piSEXP, SEXP qSEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type db(dbSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(neg_loglik_theta_ns(theta, db, y, pi, q, number_of_1_loci, number_of_2_loci));
    return rcpp_result_gen;
END_RCPP
}
// estimate_pr_ns
NumericMatrix estimate_pr_ns(IntegerMatrix x, NumericMatrix v, int number_of_1_loci, int number_of_2_loci, CharacterVector locus_names);
RcppExport SEXP _disclapmix2_estimate_pr_ns(SEXP xSEXP, SEXP vSEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP, SEXP locus_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type locus_names(locus_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_pr_ns(x, v, number_of_1_loci, number_of_2_loci, locus_names));
    return rcpp_result_gen;
END_RCPP
}
// estimate_q
NumericMatrix estimate_q(IntegerMatrix x, NumericMatrix v, DataFrame non_standard_haplotypes, int number_of_1_loci, int number_of_2_loci);
RcppExport SEXP _disclapmix2_estimate_q(SEXP xSEXP, SEXP vSEXP, SEXP non_standard_haplotypesSEXP, SEXP number_of_1_lociSEXP, SEXP number_of_2_lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type non_standard_haplotypes(non_standard_haplotypesSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_1_loci(number_of_1_lociSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_2_loci(number_of_2_lociSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_q(x, v, non_standard_haplotypes, number_of_1_loci, number_of_2_loci));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_disclapmix2_get_P", (DL_FUNC) &_disclapmix2_get_P, 3},
    {"_disclapmix2_get_tau", (DL_FUNC) &_disclapmix2_get_tau, 3},
    {"_disclapmix2_loglik_tau_p", (DL_FUNC) &_disclapmix2_loglik_tau_p, 6},
    {"_disclapmix2_loglik_tau_p_ns", (DL_FUNC) &_disclapmix2_loglik_tau_p_ns, 8},
    {"_disclapmix2_neg_loglik_theta", (DL_FUNC) &_disclapmix2_neg_loglik_theta, 5},
    {"_disclapmix2_compute_profile_prs", (DL_FUNC) &_disclapmix2_compute_profile_prs, 5},
    {"_disclapmix2_compute_profiles_pr_by_cluster_and_locus", (DL_FUNC) &_disclapmix2_compute_profiles_pr_by_cluster_and_locus, 5},
    {"_disclapmix2_compute_profile_prs_ns", (DL_FUNC) &_disclapmix2_compute_profile_prs_ns, 7},
    {"_disclapmix2_compute_posterior_cluster_prs", (DL_FUNC) &_disclapmix2_compute_posterior_cluster_prs, 2},
    {"_disclapmix2_neg_loglik_theta_ns", (DL_FUNC) &_disclapmix2_neg_loglik_theta_ns, 7},
    {"_disclapmix2_estimate_pr_ns", (DL_FUNC) &_disclapmix2_estimate_pr_ns, 5},
    {"_disclapmix2_estimate_q", (DL_FUNC) &_disclapmix2_estimate_q, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_disclapmix2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
