# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

enumerate_haplotypes <- function(alleles, number_of_alleles_per_haplotype = 1L, collapse = FALSE) {
    .Call('_disclapmixExtended_enumerate_haplotypes', PACKAGE = 'disclapmixExtended', alleles, number_of_alleles_per_haplotype, collapse)
}

get_p_jk <- function(theta, r, c) {
    .Call('_disclapmixExtended_get_p_jk', PACKAGE = 'disclapmixExtended', theta, r, c)
}

get_P <- function(theta, number_of_loci, number_of_clusters) {
    .Call('_disclapmixExtended_get_P', PACKAGE = 'disclapmixExtended', theta, number_of_loci, number_of_clusters)
}

get_tau <- function(theta, number_of_loci, number_of_clusters) {
    .Call('_disclapmixExtended_get_tau', PACKAGE = 'disclapmixExtended', theta, number_of_loci, number_of_clusters)
}

loglik_tau_p <- function(tau, p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmixExtended_loglik_tau_p', PACKAGE = 'disclapmixExtended', tau, p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci)
}

neg_loglik_theta <- function(theta, db, y, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmixExtended_neg_loglik_theta', PACKAGE = 'disclapmixExtended', theta, db, y, number_of_1_loci, number_of_2_loci)
}

compute_profile_prs <- function(p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmixExtended_compute_profile_prs', PACKAGE = 'disclapmixExtended', p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci)
}

compute_posterior_cluster_prs <- function(profile_pr, tau) {
    .Call('_disclapmixExtended_compute_posterior_cluster_prs', PACKAGE = 'disclapmixExtended', profile_pr, tau)
}

pr_disclap_scalar_x_scalar_y <- function(x, y, p) {
    .Call('_disclapmixExtended_pr_disclap_scalar_x_scalar_y', PACKAGE = 'disclapmixExtended', x, y, p)
}

average_pr_disclap_scalar_x_vector_y <- function(x, y, p) {
    .Call('_disclapmixExtended_average_pr_disclap_scalar_x_vector_y', PACKAGE = 'disclapmixExtended', x, y, p)
}

average_pr_disclap_vector_x_scalar_y <- function(x, y, p) {
    .Call('_disclapmixExtended_average_pr_disclap_vector_x_scalar_y', PACKAGE = 'disclapmixExtended', x, y, p)
}

pr_ordered_haplotype_vector_u_scalar_y <- function(u, y, p) {
    .Call('_disclapmixExtended_pr_ordered_haplotype_vector_u_scalar_y', PACKAGE = 'disclapmixExtended', u, y, p)
}

get_number_of_permutations_multiset <- function(x) {
    .Call('_disclapmixExtended_get_number_of_permutations_multiset', PACKAGE = 'disclapmixExtended', x)
}

pr_unordered_haplotype_vector_x_scalar_y_given_dims <- function(x, y, p) {
    .Call('_disclapmixExtended_pr_unordered_haplotype_vector_x_scalar_y_given_dims', PACKAGE = 'disclapmixExtended', x, y, p)
}

pr_ordered_haplotype_vector_u_vector_y_given_dims <- function(u, y, p) {
    .Call('_disclapmixExtended_pr_ordered_haplotype_vector_u_vector_y_given_dims', PACKAGE = 'disclapmixExtended', u, y, p)
}

pr_unordered_haplotype_vector_x_vector_y_given_dims <- function(x, y, p) {
    .Call('_disclapmixExtended_pr_unordered_haplotype_vector_x_vector_y_given_dims', PACKAGE = 'disclapmixExtended', x, y, p)
}

pr_unordered_haplotype_vector_x_vector_y <- function(x, y, p, q) {
    .Call('_disclapmixExtended_pr_unordered_haplotype_vector_x_vector_y', PACKAGE = 'disclapmixExtended', x, y, p, q)
}

pr_unordered_haplotype_list_x_vector_y <- function(x, y, p, q) {
    .Call('_disclapmixExtended_pr_unordered_haplotype_list_x_vector_y', PACKAGE = 'disclapmixExtended', x, y, p, q)
}

log_likelihood_y_1_allele_locus <- function(y, haplotypes, known_haplotypes_locus, p, z, clade) {
    .Call('_disclapmixExtended_log_likelihood_y_1_allele_locus', PACKAGE = 'disclapmixExtended', y, haplotypes, known_haplotypes_locus, p, z, clade)
}

log_likelihood_y_1_allele_locus_w <- function(y, y_prev, haplotypes, known_haplotypes_locus, p, w, clade) {
    .Call('_disclapmixExtended_log_likelihood_y_1_allele_locus_w', PACKAGE = 'disclapmixExtended', y, y_prev, haplotypes, known_haplotypes_locus, p, w, clade)
}

log_likelihood_y_2_allele_locus <- function(y, haplotypes, known_haplotypes_locus, p, z, clade) {
    .Call('_disclapmixExtended_log_likelihood_y_2_allele_locus', PACKAGE = 'disclapmixExtended', y, haplotypes, known_haplotypes_locus, p, z, clade)
}

log_likelihood_y_2_allele_locus_w <- function(y, y_prev, haplotypes, known_haplotypes_locus, p, w, clade) {
    .Call('_disclapmixExtended_log_likelihood_y_2_allele_locus_w', PACKAGE = 'disclapmixExtended', y, y_prev, haplotypes, known_haplotypes_locus, p, w, clade)
}

mle_y_1_allele_locus <- function(y_candidates, haplotypes, known_haplotypes_locus, p, z, clade) {
    .Call('_disclapmixExtended_mle_y_1_allele_locus', PACKAGE = 'disclapmixExtended', y_candidates, haplotypes, known_haplotypes_locus, p, z, clade)
}

mle_y_1_allele_locus_w <- function(y_candidates, y_prev, haplotypes, known_haplotypes_locus, p, w, clade) {
    .Call('_disclapmixExtended_mle_y_1_allele_locus_w', PACKAGE = 'disclapmixExtended', y_candidates, y_prev, haplotypes, known_haplotypes_locus, p, w, clade)
}

mle_y_2_allele_locus <- function(y_candidates, haplotypes, known_haplotypes_locus, p, z, clade) {
    .Call('_disclapmixExtended_mle_y_2_allele_locus', PACKAGE = 'disclapmixExtended', y_candidates, haplotypes, known_haplotypes_locus, p, z, clade)
}

mle_y_2_allele_locus_w <- function(y_candidates, y_prev, haplotypes, known_haplotypes_locus, p, w, clade) {
    .Call('_disclapmixExtended_mle_y_2_allele_locus_w', PACKAGE = 'disclapmixExtended', y_candidates, y_prev, haplotypes, known_haplotypes_locus, p, w, clade)
}

mle_y_weighted <- function(profiles, known_haplotype_summary, y_prev, disclap_parameters, y_candidates_by_locus, w) {
    .Call('_disclapmixExtended_mle_y_weighted', PACKAGE = 'disclapmixExtended', profiles, known_haplotype_summary, y_prev, disclap_parameters, y_candidates_by_locus, w)
}

log_lik_p_1_locus <- function(p_by_clade, y_by_clade, haplotypes, known_haplotypes_locus, z) {
    .Call('_disclapmixExtended_log_lik_p_1_locus', PACKAGE = 'disclapmixExtended', p_by_clade, y_by_clade, haplotypes, known_haplotypes_locus, z)
}

log_lik_p_2_locus <- function(p_by_clade, y_by_clade, haplotypes, known_haplotypes_locus, z) {
    .Call('_disclapmixExtended_log_lik_p_2_locus', PACKAGE = 'disclapmixExtended', p_by_clade, y_by_clade, haplotypes, known_haplotypes_locus, z)
}

log_lik_pjk <- function(pjk, y, profiles, known_haplotypes, z) {
    .Call('_disclapmixExtended_log_lik_pjk', PACKAGE = 'disclapmixExtended', pjk, y, profiles, known_haplotypes, z)
}

log_lik_pjk_tau <- function(pjk, y, profiles, known_haplotypes, tau) {
    .Call('_disclapmixExtended_log_lik_pjk_tau', PACKAGE = 'disclapmixExtended', pjk, y, profiles, known_haplotypes, tau)
}

pr_binom <- function(x, size, prob) {
    .Call('_disclapmixExtended_pr_binom', PACKAGE = 'disclapmixExtended', x, size, prob)
}

pr_dlme_internal <- function(profiles, known_haplotype_summary, y, disclap_parameters, tau, pr_n, pr_int, f_point, normalise_rows = FALSE) {
    .Call('_disclapmixExtended_pr_dlme_internal', PACKAGE = 'disclapmixExtended', profiles, known_haplotype_summary, y, disclap_parameters, tau, pr_n, pr_int, f_point, normalise_rows)
}

#' Export probabilities of known haplotypes per clade as table
#'
#' @param fit fit
#' @return DataFrame
#' @examples
#' # single locus, single cluster
#'y <- data.frame(locus1=11L)
#'  disclap_parameters <- matrix(0.25)
#'  
#'  dlme_parameters <- dlme_parameters(y = y, disclap_parameters = disclap_parameters)
#'  x <- sample_profiles(dlme_parameters, n = 10)
#'  fit <- disclapmix_extended(x, number_of_clades = 1L)
#'  
#'  freqs <- export_freqs(fit)
#' @export
export_freqs <- function(fit) {
    .Call('_disclapmixExtended_export_freqs', PACKAGE = 'disclapmixExtended', fit)
}

estimate_pr_point_alleles_locus_clade <- function(haplotypes, known_haplotype_summary_locus, z, i_clade) {
    .Call('_disclapmixExtended_estimate_pr_point_alleles_locus_clade', PACKAGE = 'disclapmixExtended', haplotypes, known_haplotype_summary_locus, z, i_clade)
}

estimate_pr_point_alleles_locus <- function(haplotypes, known_haplotype_summary_locus, z, number_of_clades) {
    .Call('_disclapmixExtended_estimate_pr_point_alleles_locus', PACKAGE = 'disclapmixExtended', haplotypes, known_haplotype_summary_locus, z, number_of_clades)
}

estimate_pr_point_alleles_locus_w <- function(haplotypes, known_haplotype_summary_locus, w) {
    .Call('_disclapmixExtended_estimate_pr_point_alleles_locus_w', PACKAGE = 'disclapmixExtended', haplotypes, known_haplotype_summary_locus, w)
}

estimate_pr_point_alleles <- function(profiles, known_haplotypes, z, number_of_clades) {
    .Call('_disclapmixExtended_estimate_pr_point_alleles', PACKAGE = 'disclapmixExtended', profiles, known_haplotypes, z, number_of_clades)
}

estimate_pr_point_alleles_w <- function(profiles, known_haplotypes, w) {
    .Call('_disclapmixExtended_estimate_pr_point_alleles_w', PACKAGE = 'disclapmixExtended', profiles, known_haplotypes, w)
}

estimate_pr_point_alleles_clade <- function(haplotypes_by_locus, known_haplotype_summary, z, clade) {
    .Call('_disclapmixExtended_estimate_pr_point_alleles_clade', PACKAGE = 'disclapmixExtended', haplotypes_by_locus, known_haplotype_summary, z, clade)
}

sample_disclap_1_single_given_dims <- function(p, x, n_alleles) {
    .Call('_disclapmixExtended_sample_disclap_1_single_given_dims', PACKAGE = 'disclapmixExtended', p, x, n_alleles)
}

sample_disclap_1 <- function(n, p, x = 0L) {
    .Call('_disclapmixExtended_sample_disclap_1', PACKAGE = 'disclapmixExtended', n, p, x)
}

sample_disclap_2_single_given_dims <- function(p, x, n_alleles) {
    .Call('_disclapmixExtended_sample_disclap_2_single_given_dims', PACKAGE = 'disclapmixExtended', p, x, n_alleles)
}

sample_disclap_2 <- function(n, p, x) {
    .Call('_disclapmixExtended_sample_disclap_2', PACKAGE = 'disclapmixExtended', n, p, x)
}

sample_point_alleles <- function(f_point, i_cluster, n_alleles) {
    .Call('_disclapmixExtended_sample_point_alleles', PACKAGE = 'disclapmixExtended', f_point, i_cluster, n_alleles)
}

#' Sample profiles according to the extended discrete Laplace distribution
#'
#' @param dlme_parameters Parameters
#' @param n Number of samples
#' @return Samples
#' @examples
#' y <- data.frame(locus1=c(11L,13L), locus2=c(13L,11L))
#'disclap_parameters <- matrix(c(0.2,0.3,0.3,0.2),ncol = 2)
#'# put all partial repeats in cluster 2, locus 2
#'  pr_integer <- matrix(c(1,1,1,.5),nrow = 2, dimnames = list(1:2,c("locus1","locus2")))
#'  f_point <- list(locus1=matrix(numeric(),
#'                                nrow = 2,ncol=0, byrow = TRUE),
#'                                locus2=matrix(c(0.,0.,0.25,0.75),
#'                                              nrow = 2,ncol=2, byrow = TRUE, dimnames = list(NULL,c("11.1","12.1")) ))
#'  
#'  dlme_parameters <- dlme_parameters(y = y, disclap_parameters = disclap_parameters, tau = c(0.3,0.7), pr_integer = pr_integer, f_point = f_point)
#'  
#'  x <- sample_profiles(dlme_parameters, n = 1e4)
#'  
#'# show that all point alleles are correctly sampled in cluster 2
#'table(x$locus2[attr(x,"z")==2]) 
#' table(x$locus2[attr(x,"z")==1])
#' @export
sample_profiles <- function(dlme_parameters, n) {
    .Call('_disclapmixExtended_sample_profiles', PACKAGE = 'disclapmixExtended', dlme_parameters, n)
}

tabulate_weighted <- function(bin, number_of_bins, weights) {
    .Call('_disclapmixExtended_tabulate_weighted', PACKAGE = 'disclapmixExtended', bin, number_of_bins, weights)
}

tabulate_weighted_0based <- function(bin, number_of_bins, weights) {
    .Call('_disclapmixExtended_tabulate_weighted_0based', PACKAGE = 'disclapmixExtended', bin, number_of_bins, weights)
}

normalise_tabulate_if_0based <- function(bin, number_of_bins, ifs, value) {
    .Call('_disclapmixExtended_normalise_tabulate_if_0based', PACKAGE = 'disclapmixExtended', bin, number_of_bins, ifs, value)
}

normalise_tabulate_if_0based_w <- function(bin, number_of_bins, w, clade) {
    .Call('_disclapmixExtended_normalise_tabulate_if_0based_w', PACKAGE = 'disclapmixExtended', bin, number_of_bins, w, clade)
}

estimate_pr_number_of_alleles_by_clade <- function(profiles, known_haplotypes, z, number_of_clades, MAX_NUMBER_OF_ALLELES = 5L) {
    .Call('_disclapmixExtended_estimate_pr_number_of_alleles_by_clade', PACKAGE = 'disclapmixExtended', profiles, known_haplotypes, z, number_of_clades, MAX_NUMBER_OF_ALLELES)
}

estimate_pr_number_of_alleles_by_clade_w <- function(profiles, known_haplotypes, w, MAX_NUMBER_OF_ALLELES = 5L) {
    .Call('_disclapmixExtended_estimate_pr_number_of_alleles_by_clade_w', PACKAGE = 'disclapmixExtended', profiles, known_haplotypes, w, MAX_NUMBER_OF_ALLELES)
}

estimate_pr_integer <- function(profiles, known_haplotypes, z, number_of_clades) {
    .Call('_disclapmixExtended_estimate_pr_integer', PACKAGE = 'disclapmixExtended', profiles, known_haplotypes, z, number_of_clades)
}

estimate_pr_integer_w <- function(profiles, known_haplotypes, w) {
    .Call('_disclapmixExtended_estimate_pr_integer_w', PACKAGE = 'disclapmixExtended', profiles, known_haplotypes, w)
}

validate_repeat_number <- function(x) {
    .Call('_disclapmixExtended_validate_repeat_number', PACKAGE = 'disclapmixExtended', x)
}

order_num <- function(x) {
    .Call('_disclapmixExtended_order_num', PACKAGE = 'disclapmixExtended', x)
}

sort_alleles <- function(x) {
    .Call('_disclapmixExtended_sort_alleles', PACKAGE = 'disclapmixExtended', x)
}

concatenate <- function(a, b) {
    .Call('_disclapmixExtended_concatenate', PACKAGE = 'disclapmixExtended', a, b)
}

paste <- function(x) {
    .Call('_disclapmixExtended_paste', PACKAGE = 'disclapmixExtended', x)
}

