# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_P <- function(theta, number_of_loci, number_of_clusters) {
    .Call('_disclapmix2_get_P', PACKAGE = 'disclapmix2', theta, number_of_loci, number_of_clusters)
}

get_tau <- function(theta, number_of_loci, number_of_clusters) {
    .Call('_disclapmix2_get_tau', PACKAGE = 'disclapmix2', theta, number_of_loci, number_of_clusters)
}

loglik_tau_p <- function(tau, p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmix2_loglik_tau_p', PACKAGE = 'disclapmix2', tau, p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci)
}

loglik_tau_p_ns <- function(tau, p_by_cluster_and_locus, db, y, pi, q, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmix2_loglik_tau_p_ns', PACKAGE = 'disclapmix2', tau, p_by_cluster_and_locus, db, y, pi, q, number_of_1_loci, number_of_2_loci)
}

neg_loglik_theta <- function(theta, db, y, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmix2_neg_loglik_theta', PACKAGE = 'disclapmix2', theta, db, y, number_of_1_loci, number_of_2_loci)
}

compute_profile_prs <- function(p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmix2_compute_profile_prs', PACKAGE = 'disclapmix2', p_by_cluster_and_locus, db, y, number_of_1_loci, number_of_2_loci)
}

compute_profiles_pr_by_cluster_and_locus <- function(p_by_cluster_and_locus, x, y, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmix2_compute_profiles_pr_by_cluster_and_locus', PACKAGE = 'disclapmix2', p_by_cluster_and_locus, x, y, number_of_1_loci, number_of_2_loci)
}

compute_profile_prs_ns <- function(p_by_cluster_and_locus, db, y, pi, q, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmix2_compute_profile_prs_ns', PACKAGE = 'disclapmix2', p_by_cluster_and_locus, db, y, pi, q, number_of_1_loci, number_of_2_loci)
}

compute_posterior_cluster_prs <- function(profile_pr, tau) {
    .Call('_disclapmix2_compute_posterior_cluster_prs', PACKAGE = 'disclapmix2', profile_pr, tau)
}

neg_loglik_theta_ns <- function(theta, db, y, pi, q, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmix2_neg_loglik_theta_ns', PACKAGE = 'disclapmix2', theta, db, y, pi, q, number_of_1_loci, number_of_2_loci)
}

estimate_pr_ns <- function(x, v, number_of_1_loci, number_of_2_loci, locus_names) {
    .Call('_disclapmix2_estimate_pr_ns', PACKAGE = 'disclapmix2', x, v, number_of_1_loci, number_of_2_loci, locus_names)
}

estimate_q <- function(x, v, non_standard_haplotypes, number_of_1_loci, number_of_2_loci) {
    .Call('_disclapmix2_estimate_q', PACKAGE = 'disclapmix2', x, v, non_standard_haplotypes, number_of_1_loci, number_of_2_loci)
}

